// Package tor generates the torrc that exposes the SlashNode UI and apps as Tor
// hidden services (.onion), and reads back the generated onion hostnames.
package tor

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"
)

// Service is one hidden service (Name = subdir under the data dir) exposing one
// or more ports under a single .onion address.
type Service struct {
	Name  string
	Ports []PortForward
}

// PortForward maps an onion-side virtual port to a local 127.0.0.1 port.
type PortForward struct {
	Virtual int // port reached on the .onion (e.g. 80 for web, 8332 for RPC)
	Local   int // forwarded to 127.0.0.1:<Local>
}

// Available reports whether tor is installed (and not disabled via env).
func Available() bool {
	if os.Getenv("SLASHNODE_NO_TOR") != "" {
		return false
	}
	_, err := exec.LookPath("tor")
	return err == nil
}

// Torrc renders a torrc exposing each service as a hidden service. dataDir is the
// base HiddenServiceDir parent.
func Torrc(dataDir string, services []Service) string {
	sorted := append([]Service(nil), services...)
	sort.Slice(sorted, func(i, j int) bool { return sorted[i].Name < sorted[j].Name })

	var b strings.Builder
	b.WriteString("# Generated by slashnoded — do not edit by hand.\n\n")
	for _, s := range sorted {
		dir := filepath.Join(dataDir, s.Name)
		fmt.Fprintf(&b, "HiddenServiceDir %s\n", dir)
		ports := append([]PortForward(nil), s.Ports...)
		sort.Slice(ports, func(i, j int) bool { return ports[i].Virtual < ports[j].Virtual })
		for _, p := range ports {
			fmt.Fprintf(&b, "HiddenServicePort %d 127.0.0.1:%d\n", p.Virtual, p.Local)
		}
		b.WriteString("\n")
	}
	return b.String()
}

// Write renders and writes the torrc to path (mode 0644).
func Write(path, dataDir string, services []Service) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	return os.WriteFile(path, []byte(Torrc(dataDir, services)), 0o644)
}

// Reload restarts tor so new hidden services are provisioned.
func Reload() error {
	if _, err := exec.LookPath("systemctl"); err == nil {
		return exec.Command("systemctl", "restart", "tor").Run()
	}
	return nil
}

// Onion reads a generated .onion hostname (empty if not ready yet).
func Onion(hostnameFile string) string {
	b, err := os.ReadFile(hostnameFile)
	if err != nil {
		return ""
	}
	return strings.TrimSpace(string(b))
}
