// Package caddy generates the Caddyfile that reverse-proxies the SlashNode
// front end and each installed app under its own subdomain
// (e.g. http://mempool.slashnode.local → 127.0.0.1:8999) and reloads Caddy.
package caddy

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"
)

// Route maps a hostname to a local upstream port.
type Route struct {
	Host         string
	UpstreamPort int
}

// Caddyfile renders the configuration. Each host reverse-proxies to slashnoded
// (which serves the console + the front end and proxies the rest). Sites are
// served over HTTPS (internalTLS uses Caddy's local CA for .local names;
// otherwise Let's Encrypt for a public domain).
func Caddyfile(routes []Route, internalTLS bool) string {
	sorted := append([]Route(nil), routes...)
	sort.Slice(sorted, func(i, j int) bool { return sorted[i].Host < sorted[j].Host })

	var b strings.Builder
	b.WriteString("# Generated by slashnoded — do not edit by hand.\n\n")
	for _, r := range sorted {
		fmt.Fprintf(&b, "%s {\n", r.Host)
		if internalTLS {
			b.WriteString("\ttls internal\n")
		}
		fmt.Fprintf(&b, "\treverse_proxy 127.0.0.1:%d\n}\n\n", r.UpstreamPort)
	}
	return b.String()
}

// Write renders and writes the Caddyfile to path (mode 0644).
func Write(path string, routes []Route, internalTLS bool) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	return os.WriteFile(path, []byte(Caddyfile(routes, internalTLS)), 0o644)
}

// Available reports whether Caddy is installed (and not disabled via env).
func Available() bool {
	if os.Getenv("SLASHNODE_NO_CADDY") != "" {
		return false
	}
	_, err := exec.LookPath("caddy")
	return err == nil
}

// Reload applies the Caddyfile (systemctl reload if available, else caddy reload).
func Reload(path string) error {
	if _, err := exec.LookPath("systemctl"); err == nil {
		if err := exec.Command("systemctl", "reload", "caddy").Run(); err == nil {
			return nil
		}
	}
	return exec.Command("caddy", "reload", "--config", path).Run()
}
