// Package caddy generates the Caddyfile that reverse-proxies the SlashNode
// front end and each installed app under its own subdomain
// (e.g. http://mempool.slashnode.local → 127.0.0.1:8999) and reloads Caddy.
package caddy

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"
)

// Route reverse-proxies an HTTPS site to a local upstream port. ListenPort 0 is
// the default HTTPS port (443) bound to Host; a non-zero ListenPort makes Caddy
// terminate TLS on that dedicated port (so apps get HTTPS uniformly on a domain,
// an mDNS name, or a bare IP — no per-app DNS needed).
type Route struct {
	Host         string
	ListenPort   int
	UpstreamPort int
}

// Caddyfile renders the configuration. Caddy terminates TLS and reverse-proxies
// to each plain-HTTP upstream, setting X-Forwarded-Proto so the app knows it is
// reached over HTTPS. internalTLS uses Caddy's local CA (for .local names and
// bare IPs); otherwise Let's Encrypt for a public domain.
func Caddyfile(routes []Route, internalTLS bool) string {
	sorted := append([]Route(nil), routes...)
	sort.Slice(sorted, func(i, j int) bool {
		if sorted[i].ListenPort != sorted[j].ListenPort {
			return sorted[i].ListenPort < sorted[j].ListenPort
		}
		return sorted[i].Host < sorted[j].Host
	})

	var b strings.Builder
	b.WriteString("# Generated by slashnoded — do not edit by hand.\n\n")
	for _, r := range sorted {
		var addr string
		switch {
		case r.ListenPort == 0:
			addr = r.Host // default HTTPS (443) for this host
		case internalTLS:
			// Any host on this port, served with the local CA — works for a bare
			// IP and mDNS name alike.
			addr = fmt.Sprintf("https://:%d", r.ListenPort)
		default:
			addr = fmt.Sprintf("https://%s:%d", r.Host, r.ListenPort)
		}
		fmt.Fprintf(&b, "%s {\n", addr)
		if internalTLS {
			b.WriteString("\ttls internal\n")
		}
		fmt.Fprintf(&b, "\treverse_proxy 127.0.0.1:%d\n}\n\n", r.UpstreamPort)
	}
	return b.String()
}

// Write renders and writes the Caddyfile to path (mode 0644).
func Write(path string, routes []Route, internalTLS bool) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	return os.WriteFile(path, []byte(Caddyfile(routes, internalTLS)), 0o644)
}

// Available reports whether Caddy is installed (and not disabled via env).
func Available() bool {
	if os.Getenv("SLASHNODE_NO_CADDY") != "" {
		return false
	}
	_, err := exec.LookPath("caddy")
	return err == nil
}

// Reload applies the Caddyfile (systemctl reload if available, else caddy reload).
func Reload(path string) error {
	if _, err := exec.LookPath("systemctl"); err == nil {
		if err := exec.Command("systemctl", "reload", "caddy").Run(); err == nil {
			return nil
		}
	}
	return exec.Command("caddy", "reload", "--config", path).Run()
}
